name: ETL pipeline

on:
  push:
    branches:
      - main

jobs:
  extract-data-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "hi"

  transform-data-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "Transforming data..."
  load-data-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "Loading data..."