name: ETL pipeline

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "hi"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "hello..."
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "byee..."
  job4:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "welcomw..."
  job5:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "heyyy..."
  job6:
    runs-on: ubuntu-latest
    needs: [job4,job5]
    steps:
      - uses: actions/checkout@v4
        name: print M
      - run: echo "good..."